### ISSUE TITLE
Seconds argument for Routes question

### ISSUE THREAD

**Issue by erwindon** [maerteijn/SaltGUI#21]
in `saltgui/static/scripts/router.js`, the instances of `LoginRoute`, `HomeRoute` and `JobRoute` are created with `this.api` as an additional argument. But that argument seems to be unused. Is that a correct observation?

**Comment by maerteijn** [comment]
Seems like a correct observation as I see nothing is done with it in the constructor(s). So maybe we can delete this indeed.
