### ISSUE TITLE
Use LET instead of VAR

### ISSUE THREAD

**Issue by erwindon** [maerteijn/SaltGUI#44]
I'm confusing myself often with the different use of `let` and `var`. Most of the new code that was contributed lately uses `let`. Would a PR where most of the `var` occurrences are replaced by `let` be acceptable?

For viewers that want more details: see https://stackoverflow.com/questions/762011/whats-the-difference-between-using-let-and-var-to-declare-a-variable-in-jav

**Comment by maerteijn** [comment]
Fix in #47
