### ISSUE TITLE
Use CONSTs whenever possible

### ISSUE THREAD

**Issue by erwindon** [maerteijn/SaltGUI#48]
Recently, all code was migrated to use `LET` only (instead of `VAR`).
The next step is to mark variables that are only assigned only once as `CONST`.
From the report, that is the majority of the assignments.

Report with `"prefer-const": 2`:

`SaltGUI/saltgui/static/scripts/api.js`
`   14:9   error  'cmdbox' is never reassigned. Use 'const' instead           prefer-const`
`   59:9   error  'button' is never reassigned. Use 'const' instead           prefer-const`
`   61:9   error  'output' is never reassigned. Use 'const' instead           prefer-const`
`   63:9   error  'target' is never reassigned. Use 'const' instead           prefer-const`
`   64:9   error  'command' is never reassigned. Use 'const' instead          prefer-const`
`   66:9   error  'func' is never reassigned. Use 'const' instead             prefer-const`
`   79:9   error  'response' is never reassigned. Use 'const' instead         prefer-const`
`   81:9   error  'outputContainer' is never reassigned. Use 'const' instead  prefer-const`
`   85:9   error  'button' is never reassigned. Use 'const' instead           prefer-const`
`   90:9   error  'manualRun' is never reassigned. Use 'const' instead        prefer-const`
`  102:9   error  'manualRun' is never reassigned. Use 'const' instead        prefer-const`
`  109:9   error  'command' is never reassigned. Use 'const' instead          prefer-const`
`  110:9   error  'output' is never reassigned. Use 'const' instead           prefer-const`
`  123:9   error  'params' is never reassigned. Use 'const' instead           prefer-const`
`  135:9   error  'api' is never reassigned. Use 'const' instead              prefer-const`
`  137:9   error  'params' is never reassigned. Use 'const' instead           prefer-const`
`  144:9   error  'type' is never reassigned. Use 'const' instead             prefer-const`
`  176:9   error  'errLabel' is never reassigned. Use 'const' instead         prefer-const`
`  194:9   error  'args' is never reassigned. Use 'const' instead             prefer-const`
`  197:9   error  'params' is never reassigned. Use 'const' instead           prefer-const`
`  199:9   error  'ret' is never reassigned. Use 'const' instead              prefer-const`
`  211:9   error  'functionToRun' is never reassigned. Use 'const' instead    prefer-const`
`  251:9   error  'location' is never reassigned. Use 'const' instead         prefer-const`
`  252:9   error  'token' is never reassigned. Use 'const' instead            prefer-const`
`  254:9   error  'headers' is never reassigned. Use 'const' instead          prefer-const`
`  264:9   error  'onFetchResponse' is never reassigned. Use 'const' instead  prefer-const`
`  267:11  error  'options' is never reassigned. Use 'const' instead          prefer-const`

`SaltGUI/saltgui/static/scripts/documentation.js`
`  52:9  error  'button' is never reassigned. Use 'const' instead  prefer-const`
`  54:9  error  'output' is never reassigned. Use 'const' instead  prefer-const`

`SaltGUI/saltgui/static/scripts/dropdown.js`
`  41:13  error  'chld' is never reassigned. Use 'const' instead            prefer-const`
`  42:11  error  'verifyCallback' is never reassigned. Use 'const' instead  prefer-const`
`  57:9   error  'button' is never reassigned. Use 'const' instead          prefer-const`

`SaltGUI/saltgui/static/scripts/output.js`
`   92:13  error  'hostname' is never reassigned. Use 'const' instead               prefer-const`
`   94:11  error  'output' is never reassigned. Use 'const' instead                 prefer-const`
`  107:15  error  'key' is never reassigned. Use 'const' instead                    prefer-const`
`  153:13  error  'hostname' is never reassigned. Use 'const' instead               prefer-const`
`  171:11  error  'hostResponse' is never reassigned. Use 'const' instead           prefer-const`
`  172:15  error  'key' is never reassigned. Use 'const' instead                    prefer-const`
`  195:11  error  'savedDocumentation' is never reassigned. Use 'const' instead     prefer-const`
`  211:13  error  'hostname' is never reassigned. Use 'const' instead               prefer-const`
`  213:11  error  'hostResponse' is never reassigned. Use 'const' instead           prefer-const`
`  215:15  error  'key' is never reassigned. Use 'const' instead                    prefer-const`
`  265:13  error  'hostname' is never reassigned. Use 'const' instead               prefer-const`
`  306:9   error  'commandArg' is never reassigned. Use 'const' instead             prefer-const`
`  307:9   error  'isDocumentationOutput' is never reassigned. Use 'const' instead  prefer-const`

`SaltGUI/saltgui/static/scripts/parsecmdline.js`
`  44:9   error  'firstEqualSign' is never reassigned. Use 'const' instead  prefer-const`
`  84:13  error  's' is never reassigned. Use 'const' instead               prefer-const`

`SaltGUI/saltgui/static/scripts/router.js`
`  19:9   error  'router' is never reassigned. Use 'const' instead     prefer-const`
`  35:11  error  'route' is never reassigned. Use 'const' instead      prefer-const`
`  45:9   error  'router' is never reassigned. Use 'const' instead     prefer-const`
`  52:9   error  'elem' is never reassigned. Use 'const' instead       prefer-const`
`  56:9   error  'afterLoad' is never reassigned. Use 'const' instead  prefer-const`

`SaltGUI/saltgui/static/scripts/routes/job.js`
`  11:9   error  'job' is never reassigned. Use 'const' instead        prefer-const`
`  20:9   error  'job' is never reassigned. Use 'const' instead        prefer-const`
`  21:9   error  'info' is never reassigned. Use 'const' instead       prefer-const`
`  28:9   error  'container' is never reassigned. Use 'const' instead  prefer-const`
`  32:9   error  'hostnames' is never reassigned. Use 'const' instead  prefer-const`
`  49:9   error  'host' is never reassigned. Use 'const' instead       prefer-const`
`  53:11  error  'task' is never reassigned. Use 'const' instead       prefer-const`
`  63:11  error  'data' is never reassigned. Use 'const' instead       prefer-const`
`  64:11  error  'task' is never reassigned. Use 'const' instead       prefer-const`

`SaltGUI/saltgui/static/scripts/routes/keys.js`
`   19:9  error  'keys' is never reassigned. Use 'const' instead      prefer-const`
`   30:9  error  'keys' is never reassigned. Use 'const' instead      prefer-const`
`   89:9  error  'element' is never reassigned. Use 'const' instead   prefer-const`
`   94:9  error  'menu' is never reassigned. Use 'const' instead      prefer-const`
`  102:9  error  'element' is never reassigned. Use 'const' instead   prefer-const`
`  104:9  error  'menu' is never reassigned. Use 'const' instead      prefer-const`
`  110:9  error  'element' is never reassigned. Use 'const' instead   prefer-const`
`  114:9  error  'rejected' is never reassigned. Use 'const' instead  prefer-const`
`  121:9  error  'menu' is never reassigned. Use 'const' instead      prefer-const`
`  129:9  error  'element' is never reassigned. Use 'const' instead   prefer-const`
`  133:9  error  'denied' is never reassigned. Use 'const' instead    prefer-const`
`  140:9  error  'menu' is never reassigned. Use 'const' instead      prefer-const`
`  149:9  error  'element' is never reassigned. Use 'const' instead   prefer-const`
`  153:9  error  'pre' is never reassigned. Use 'const' instead       prefer-const`
`  160:9  error  'menu' is never reassigned. Use 'const' instead      prefer-const`

`SaltGUI/saltgui/static/scripts/routes/login.js`
`  16:9  error  'typeItem' is never reassigned. Use 'const' instead    prefer-const`
`  26:9  error  'typeItem' is never reassigned. Use 'const' instead    prefer-const`
`  39:9  error  'submit' is never reassigned. Use 'const' instead      prefer-const`
`  47:9  error  'username' is never reassigned. Use 'const' instead    prefer-const`
`  48:9  error  'password' is never reassigned. Use 'const' instead    prefer-const`
`  58:9  error  'notice' is never reassigned. Use 'const' instead      prefer-const`
`  60:9  error  'success' is never reassigned. Use 'const' instead     prefer-const`
`  78:9  error  'notice' is never reassigned. Use 'const' instead      prefer-const`
`  80:9  error  'authFailed' is never reassigned. Use 'const' instead  prefer-const`

`SaltGUI/saltgui/static/scripts/routes/minions.js`
`  17:9  error  'minions' is never reassigned. Use 'const' instead    prefer-const`
`  28:9  error  'keys' is never reassigned. Use 'const' instead       prefer-const`
`  30:9  error  'list' is never reassigned. Use 'const' instead       prefer-const`
`  32:9  error  'hostnames' is never reassigned. Use 'const' instead  prefer-const`
`  50:9  error  'element' is never reassigned. Use 'const' instead    prefer-const`
`  51:9  error  'menu' is never reassigned. Use 'const' instead       prefer-const`

`SaltGUI/saltgui/static/scripts/routes/page.js`
`    7:11  error  'header' is never reassigned. Use 'const' instead        prefer-const`
`    8:11  error  'menu' is never reassigned. Use 'const' instead          prefer-const`
`   16:13  error  'api' is never reassigned. Use 'const' instead           prefer-const`
`   24:9   error  'minions' is never reassigned. Use 'const' instead       prefer-const`
`   26:9   error  'list' is never reassigned. Use 'const' instead          prefer-const`
`   27:9   error  'hostnames' is never reassigned. Use 'const' instead     prefer-const`
`   30:11  error  'minion_info' is never reassigned. Use 'const' instead   prefer-const`
`   36:13  error  'minion' is never reassigned. Use 'const' instead        prefer-const`
`   69:9   error  'element' is never reassigned. Use 'const' instead       prefer-const`
`   73:9   error  'offline' is never reassigned. Use 'const' instead       prefer-const`
`   79:9   error  'ip' is never reassigned. Use 'const' instead            prefer-const`
`   81:9   error  'element' is never reassigned. Use 'const' instead       prefer-const`
`   85:9   error  'address' is never reassigned. Use 'const' instead       prefer-const`
`  107:9   error  'minion' is never reassigned. Use 'const' instead        prefer-const`
`  118:9   error  'element' is never reassigned. Use 'const' instead       prefer-const`
`  126:9   error  'jobContainer' is never reassigned. Use 'const' instead  prefer-const`
`  128:9   error  'jobs' is never reassigned. Use 'const' instead          prefer-const`
`  135:11  error  'job' is never reassigned. Use 'const' instead           prefer-const`
`  152:9   error  'element' is never reassigned. Use 'const' instead       prefer-const`
`  163:9   error  'router' is never reassigned. Use 'const' instead        prefer-const`
`  170:9   error  'keys' is never reassigned. Use 'const' instead          prefer-const`
`  171:9   error  'newArray' is never reassigned. Use 'const' instead      prefer-const`
`  174:11  error  'key' is never reassigned. Use 'const' instead           prefer-const`
`  175:11  error  'job' is never reassigned. Use 'const' instead           prefer-const`
`  194:9   error  'target' is never reassigned. Use 'const' instead        prefer-const`
`  195:9   error  'selection' is never reassigned. Use 'const' instead     prefer-const`
`  196:9   error  'range' is never reassigned. Use 'const' instead         prefer-const`
`  206:9   error  'target' is never reassigned. Use 'const' instead        prefer-const`
`  207:9   error  'command' is never reassigned. Use 'const' instead       prefer-const`

`SaltGUI/saltgui/static/scripts/routes/route.js`
`  28:9  error  'div' is never reassigned. Use 'const' instead  prefer-const`

`SaltGUI/saltgui/static/scripts/utils.js`
`   3:9   error  'secondsPassed' is never reassigned. Use 'const' instead  prefer-const`
`  10:11  error  'minutes' is never reassigned. Use 'const' instead        prefer-const`
`  15:11  error  'hours' is never reassigned. Use 'const' instead          prefer-const`
`  24:11  error  'days' is never reassigned. Use 'const' instead           prefer-const`
`  37:7   error  'element' is never reassigned. Use 'const' instead        prefer-const`
`  44:7   error  'vars' is never reassigned. Use 'const' instead           prefer-const`
`  45:7   error  'hashes' is never reassigned. Use 'const' instead         prefer-const`
`  55:7   error  'div' is never reassigned. Use 'const' instead            prefer-const`

`SaltGUI/tests/functional/login.js`
`  15:9   error  'options' is never reassigned. Use 'const' instead    prefer-const`
`  49:11  error  'selector' is never reassigned. Use 'const' instead   prefer-const`
`  73:15  error  'loginpage' is never reassigned. Use 'const' instead  prefer-const`
`  92:15  error  'loginpage' is never reassigned. Use 'const' instead  prefer-const`
`  98:15  error  'loginpage' is never reassigned. Use 'const' instead  prefer-const`

`SaltGUI/tests/unit/output.js`
`  3:5  error  'Output' is never reassigned. Use 'const' instead  prefer-const`

`SaltGUI/tests/unit/utils.js`
`  13:9  error  'now' is never reassigned. Use 'const' instead  prefer-const`
`  51:9  error  'now' is never reassigned. Use 'const' instead  prefer-const`

**Comment by maerteijn** [comment]
You already let jslint do the work :)
