### ISSUE TITLE
No Linux? No lsb_distrib_description

### ISSUE THREAD

**Issue by hbokh** [maerteijn/SaltGUI#5]
Non-Linux minions like FreeBSD show up as `undefined` because they do not make use of LSB / `lsb_distrib_description`.
Is it an option to include another or a different grain e.g. `os` or `os_family`?

**Comment by maerteijn** [comment]
Good suggestion. Will fix this in the following week(s) when I will be working on the project

**Comment by erwindon** [comment]
I've added a PR to fix this (uses os+osrelease)

**Comment by maerteijn** [comment]
Fixed in #10
