### ISSUE TITLE
How to store jobs by StartTime?

### ISSUE THREAD

**Issue by judexzhu** [maerteijn/SaltGUI#6]
Hi Thank you for the simple but nice Salt-GUI, it's really good to check the job result after.

But it is not sorted by the start time, how can I store the Recent Jobs list by the time.

Thanks 

![image](https://user-images.githubusercontent.com/17834225/37515728-ba87d07a-2946-11e8-95da-4684363e1d11.png)

**Comment by maerteijn** [comment]
I think we need to do this in javascript, as I think the REST API will not sort it. I'll mark this issue and will fix it when I have time

**Comment by maerteijn** [comment]
Fixed in b81df10af9ea72f27eddb71fa125e5fddcbce06f
