### ISSUE TITLE
Recent jobs result

### ISSUE THREAD

**Issue by dynek** [maerteijn/SaltGUI#7]
Hello,

First of all, great idea to maintain a GUI for Salt. Finally one! :-) Thanks you.

Question: When I check the result of a highstate I actually see the JSON associated with the job and not the pretty output you are showing on the screenshots. I have just cloned master.

Thank you

**Comment by maerteijn** [comment]
I've taken over the project from somebody else, the screenshots are there I think for what it could be, not what it is :)
