### ISSUE TITLE
Recommendation for readme.md

### ISSUE THREAD

**Issue by bradpoulton** [maerteijn/SaltGUI#8]
Can you add "rest_cherrypy:"

rest_cherrypy:
  port: 8000
  host: 0.0.0.0
  disable_ssl: true
  app: /srv/salt-gui/index.html
  static: /srv/salt-gui/static
  static_path: /static

to your readme.md file? it would have saved me 5 minutes of googling. thanks

**Comment by erwindon** [comment]
I've added a PR to fix this

**Comment by maerteijn** [comment]
Fixed in #10
