### ISSUE TITLE
Recommendation for readme.md

### ISSUE THREAD

**Issue by bradpoulton** [maerteijn/SaltGUI#9]
Can you change this:

  port: 8000
  host: 0.0.0.0
  disable_ssl: true
  app: /srv/salt-gui/index.html
  static: /srv/salt-gui/static
  static_path: /static

to this:

  port: 8000
  host: 0.0.0.0
  disable_ssl: true
  app: /srv/saltgui/index.html
  static: /srv/saltgui/static
  static_path: /static

in your readme.md file? The default folder name is saltgui when pulled down with git clone. Thanks

**Comment by erwindon** [comment]
I've added a PR to fix this

**Comment by maerteijn** [comment]
Duplicate of  #8
